### ISSUE TITLE
Ensure working correctly with CI

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/boot-cljs-test#12]
1. Test that return code from doo is exposed
2. Test that it composes with `.clj` test task

(1) Seems to not be working:

```
$ boot test     
. . .                                                                                                                                                   
1 failures, 0 errors.
$  echo $?
0
```

**Comment by crisptrutski** [comment]
Closing as (1) was just misuses (forgot `:exit?` flag), and (2) can go into #13

**Comment by dgellow** [comment]
Could you show me how you solved (1) ?

I have the same problem that you had, the return code is not exposed, but I am already using `:exit?` (I also tried via the `-x` flag from the CLI).

I have a task `run-tests` like this

``` clojure
(deftask run-tests []
  (set-env! :source-paths #{"src" "test"})
  (task-options! test-cljs {:exit? true})
  (comp (test-cljs)))
```

You can see the whole file [here](https://github.com/dgellow/boot-cljs-experiments/blob/master/build.boot#L31).

I have the following output

``` sh
$ boot -s test test-cljs -x  
Writing suite.cljs...
Writing output.cljs.edn...
Compiling ClojureScript...
? output.js
Running cljs tests...
. . . 
Testing com.aztrana.webclient.tests

FAIL in (failing-test) (:)
expected: (= 1 2)
  actual: (not (= 1 2))

Testing cljs.user

Testing clojure.template

Ran 2 tests containing 2 assertions.
1 failures, 0 errors.
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///var/folders/vz/95lm17qs30bg2r8ndn0y97l40000gn/T/phantom7423540207382186989.js. Domains, protocols and ports must match.

$ echo $?
0
```

I'm getting the same behaviour via my `run-tests` task.

Am I doing something wrong?

**Comment by crisptrutski** [comment]
@dgellow doing nothing wrong, as pointed out by @thedavidmeister this was actually still broken :disappointed:

**Comment by dgellow** [comment]
@crisptrutski Could you publish a new version on clojar with the fix?

**Comment by crisptrutski** [comment]
Sure, just published it

**Comment by dgellow** [comment]
thank you! :+1: 🌭
