### ISSUE TITLE
Add examples, and run via circleci or travis

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/boot-cljs-test#13]
@pandeiro hands welcome :)

@martinklepsch case combined with dev build would be great. any other examples worthwhile?

**Comment by crisptrutski** [comment]
- Testing that it composes with a regular `boot-test` task

**Comment by thedavidmeister** [comment]
```
          (run-cljs-tests :out-file out-file
                          :cljs-opts cljs-opts
                          :js-env js-env
                          :exit exit?))))
```

As per #12 it looks like the final line here should be:

`:exit? exit?` right? Otherwise we don't pass through the flag properly and then we don't get the exit code and then Travis always passes even if tests fail.

**Comment by crisptrutski** [comment]
Quite right, thanks! c335b32782a0155317c72ffbc10996adad122fb5
