### ISSUE TITLE
Running in node?

### ISSUE THREAD

**Issue by julienfantin** [crisptrutski/boot-cljs-test#15]
I have a test suite that runs and passes with `{:js-env :phantom}`, however with this task:

``` clojure
(deftask run-cljs-node-tests
  "Run cljs node.js tests"
  []
  (task-options! test-cljs {:js-env :node})
  (test-cljs))
```

I got the following error message:

```
boot testing run-cljs-node-tests
             clojure.lang.ExceptionInfo: java.lang.AssertionError: Assert failed: node should be used with :target :nodejs and :hashbang false
                                         (and (= :nodejs (:target opts)) (false? (:hashbang opts)))
    data: {:file
           "/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/boot.user3520479088789272618.clj",
           :line 57}
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: node should be used with :target :nodejs and :hashbang false
                                         (and (= :nodejs (:target opts)) (false? (:hashbang opts)))
               java.lang.AssertionError: Assert failed: node should be used with :target :nodejs and :hashbang false
                                         (and (= :nodejs (:target opts)) (false? (:hashbang opts)))
          doo.core/assert-compiler-opts                          core.clj:  103
                                    ...                                        
crisptrutski.boot-cljs-test/eval1483/fn                boot_cljs_test.clj:   88
                                    ...                                        
crisptrutski.boot-cljs-test/eval1515/fn                boot_cljs_test.clj:  137
                                    ...                                        
                     clojure.core/apply                          core.clj:  630
            boot.user/eval1677/fn/fn/fn  boot.user3520479088789272618.clj:   51
                                    ...                                        
                  boot.user/eval1677/fn  boot.user3520479088789272618.clj:   51
                                    ...                                        
                     clojure.core/apply                          core.clj:  630
              boot.core/construct-tasks                          core.clj:  684
                                    ...                                        
                     clojure.core/apply                          core.clj:  630
                      boot.core/boot/fn                          core.clj:  712
    clojure.core/binding-conveyor-fn/fn                          core.clj: 1916
                                    ...                                        

```

Updating the options to match what was suggested with `{:js-env :nodejs}`, gives different error:

```
boot testing run-cljs-node-tests
Writing suite.cljs...
Writing output.cljs.edn...
Compiling ClojureScript...
• output.js
Running cljs tests...             clojure.lang.ExceptionInfo: java.lang.AssertionError: Assert failed: (valid-js-env? js-env)
    data: {:file
           "/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/boot.user7375995942041478656.clj",
           :line 57}
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: (valid-js-env? js-env)
               java.lang.AssertionError: Assert failed: (valid-js-env? js-env)
                          doo.core/run-script            core.clj:  123
                                          ...                          
crisptrutski.boot-cljs-test/eval1483/fn/fn/fn  boot_cljs_test.clj:   98
           adzerk.boot-cljs/eval1333/fn/fn/fn       boot_cljs.clj:  199
           adzerk.boot-cljs/eval1291/fn/fn/fn       boot_cljs.clj:  133
crisptrutski.boot-cljs-test/eval1453/fn/fn/fn  boot_cljs_test.clj:   75
                          boot.core/run-tasks            core.clj:  701
                            boot.core/boot/fn            core.clj:  711
          clojure.core/binding-conveyor-fn/fn            core.clj: 1916
                                          ...                          

```

Am I missing something on how to setup the node env?

**Comment by dgellow** [comment]
Just to say, I have the exact same problem and I am also looking for a solution to run my tests within node.

**Comment by crisptrutski** [comment]
Hey @julienfantin @dgellow, thanks for reporting this.

Your original code is correct, `:node` is the correct term for the underlying testing library, [doo](https://github.com/bensu/doo). Changing this value, besides leading to the failed assertion in doo you posted (`:nodejs` is not a supported value), does not actually change the value of `:target` sent to the Clojurescript compiler.

While it's possible to work around this using the "advanced usage" form, where you provide you can control compilation yourself, I'll make a quick release now for this to "just work" anyway

**Comment by crisptrutski** [comment]
Just a quick update - there's a small snag that the bootstrapping code CLJS emits for node seems to assume that you're running the script from the folder, and you'll get an error like:

```
{ [Error: Cannot find module 'PROJECT-PATH/output.out/goog/bootstrap/nodejs.js'] 
  code: 'MODULE_NOT_FOUND''}
```

The path really should be `BOOT-TMP-DIR/output.out/goog/bootstrap/nodejs.js`.

Will look into this further tomorrow - but some possible workarounds:
1. Copy the two bootstrapping files ("output.out/goog/bootstrap/nodejs.js" and "output.out/cljs_deps.js") from your boot temporary files to your project path, OR
2. Use a custom build of Clojurescript with lines https://github.com/clojure/clojurescript/blame/82a3c14c09b54124b8e788d5649cd129a43d80b9/src/main/clojure/cljs/closure.clj#L1147-L1148 changed to replace `path.resolve('.')` with `path.dirname(__filename)`

**Comment by crisptrutski** [comment]
After some further thought the CLJS behaviour makes sense - it's just assuming that you are running `node` from the same path you compiled from. The (2) workaround above would probably break builds with paths in their `:output-to` parameter. And (1) is totally impractical.

This seems like a generic issue executing node-targeted JS with boot, perhaps @Deraen has some wisdom? I'm quite behind the times on both CLJS and boot at the moment :disappointed:

**Comment by martinklepsch** [comment]
@crisptrutski I've encountered the same issue when writing the node part of an electron app. There is a ticket in jira about the resolve(.) thing. @bensu was working on a solution it I think.

See this for details https://github.com/martinklepsch/electron-and-clojurescript/blob/master/build.boot#L29

**Comment by crisptrutski** [comment]
@martinklepsch thanks for the intel! Not sure I can use that `asset-path` trick, as currently my approach is to run the files directly from the fileset, to play nicely with `watch` - won't have access to that absolute path until _after_ running boot-cljs, right?

**Comment by crisptrutski** [comment]
Maybe another option would be to have a `doo` parameter for setting the path a runner is executed from? @bensu

**Comment by bensu** [comment]
Hhhmm this is tricky. I would love to help define the compiler's behavior first. The relevant issues are:

http://dev.clojure.org/jira/browse/CLJS-1444
http://dev.clojure.org/jira/browse/CLJS-1466

CLJS-1466 could use some testing. The patch is ready but since there is change of breakage, David is waiting for user input on it.

I apologize but I'm running behind with `doo` (travelling). I'll be back next week.

**Comment by crisptrutski** [comment]
Seems that this would also be resolved by #21 if bensu/doo#68 is accepted

**Comment by crisptrutski** [comment]
@julienfantin @dgellow let me know if`[crisptrutski/boot-cljs-test "0.2.1-SNAPSHOT"]` solves this issue for you, and I'll cut a release :smile:

**Comment by crisptrutski** [comment]
Closing, since it's working in my own testing. Feel free to reopen

**Comment by dgellow** [comment]
Hey @crisptrutski,

I've tested v`0.2.1-SNAPSHOT`, it works for me 👍
