### ISSUE TITLE
Running in multiple environments?

### ISSUE THREAD

**Issue by julienfantin** [crisptrutski/boot-cljs-test#16]
Could you add some general instructions on how to run a test-suite in multiple environments with the lower-level tasks?

I'm trying to have a task compose phantom and browser tests, but the second task picks up the js files of the first one and gives an error. 

Right now I can only get both environments to work by running the individuals test tasks separately in their own boot invocation, and cleaning up the target-path in between. Though this could probably be automated, it doesn't even sound like the right way to do this!

Cheers

**Comment by crisptrutski** [comment]
Hey @julienfantin, would be glad to show you an example, but I'd like to understand your use case a bit more. 

When I've used the lower-level tasks, my purpose was actually to compile the code under test just once, and use that for multiple test runner calls. When you complain about existing JS files, are you wanting to actually compile different builds, or do you mean you're stumbling over the generated test runner files?

Something that occurs to me is that the `test-cljs` task could be made to pass on the _original_ fileset after running the tests, in which case you could compose consecutive runs without any fear.

**Comment by crisptrutski** [comment]
Supporting this use case by defaulting to passing on an unchanged fileset in e29f36c9324ce122eb4ad8f05393de5d6708bf67 on the #24 branch
