### ISSUE TITLE
show test output as it is available

### ISSUE THREAD

**Issue by thedavidmeister** [crisptrutski/boot-cljs-test#20]
If you just have `Running cljs tests...` with no further output for 10 minutes or more, Travis will cancel and fail the whole build.

All you need to do to avoid this is make sure there is output to the terminal more than once per 10 minutes.

**Comment by crisptrutski** [comment]
Thanks for reporting - this sounds like an upstream issue, but I'll take a look and follow up :+1:

**Comment by bensu** [comment]
@crisptrutski I added behavior for this here https://github.com/bensu/doo/commit/41f5c3294dd505265488b4f03a56a33c73c4e63a
which is available in `0.1.6`

**Comment by crisptrutski** [comment]
@bensu nice work! 

@thedavidmeister pushed `[crisptrutski/boot-cljs-test "0.2.1-SNAPSHOT"]`, would you mind trying it out? 

Note that `{:optimizations :none}` will not work yet, I need to figure out how that'll work with the latest version of doo.

**Comment by crisptrutski** [comment]
The awesome `[doo "0.1.6"]` has been released, and latest `boot-cljs-test` is getting this for free :tada:
