### ISSUE TITLE
bad interaction with boot-test?

### ISSUE THREAD

**Issue by magomimmo** [crisptrutski/boot-cljs-test#22]
Hi, I'm trying to use `boot-cljs-test` in a pipeline with `boot-test`. My goal is to be able to simultaneously run CLJ and CLJS test, even when using portable `.cljc` files.  The pipeline could be something like this:

``` bash
boot testing test-cljs -n <a portable namespace> test -n <a portable namespce>
```

The above `testing` task only adds `test/cljc` dir to `:source-paths` env variable. As soon as I remove the `-n` option like so:

``` bash
boot testing test-cljs test
```

The `test` task evaluates two times any portable namespace (i.e. any `.cljc` file). Moreover, if I prepend `test` to `test-cljs` in the boot pipeline (e.g. `boot test test-cljs`) the above duplication effect disappears.  The problem with this simple solution is that if any CLJ test assertion fails, `test` raises an exception and the `test-cljs` is not triggered until the failed assertion is solved. 

Is there any clue for this testing scenario?

**Comment by crisptrutski** [comment]
Thanks for reporting this @magomimmo - this issue definitely needs fixing, and I'm on the case :mag_right:

**Comment by magomimmo** [comment]
Thanks so much, I appreciate

**Comment by crisptrutski** [comment]
This issue will be solved via overlap through any one of these other issues:
1. Upstream issue that `boot-test` should not repeat tests for modified files (adzerk-oss/boot-test#18)
2. By default `boot-cljs-test` will "not modify" the fileset (#16)
3. Options to generate reliable namespace parameters, which will also dedupe (#23)
