### ISSUE TITLE
By default remap paths to executables in `node_modules`

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/boot-cljs-test#31]
The downside of `:exec-dir` - more work to use locally installed npm tools

**Comment by Deraen** [comment]
I wrote about this on other issue: https://github.com/crisptrutski/boot-cljs-test/issues/30#issuecomment-169159293

**Comment by anmonteiro** [comment]
This could also be supported for other envs such as Node. @Deraen 's WIP patch seems to only cover the functionality for Karma

**Comment by crisptrutski** [comment]
Perhaps as a quick workaround `boot-cljs-test` could copy any `node_modules` directory found on the classpath to the `:exec-dir`?

**Comment by anmonteiro** [comment]
here's what I'm doing currently (might serve as future reference):

``` clojure

(deftask add-node-modules []
  (with-pre-wrap fileset
    (let [nm (io/file "node_modules")]
      (-> fileset
        (add-resource (io/file ".") :include #{#"^node_modules/"})
        commit!))))
```

This ends up in `:exec-dir` because it's added as a `resource` (e.g. `add-asset` won't work), but it's relying a bit on Boot's implementation details.

**Comment by crisptrutski** [comment]
Brought in a basic version using `io/copy` - when the generated JS is in a subfolder (ie. using multiple segment ids as boot-cljs recommends) I wasn't sure how to adapt above trick. Seems fast enough with Karma + required plugins, but can look at optimising later.

**Comment by anmonteiro** [comment]
Just had the chance to test this with `0.3.0-SNAPSHOT` and it's working great in Node.
