### ISSUE TITLE
All namespaces compiled and loaded unnecessarily

### ISSUE THREAD

**Issue by Deraen** [crisptrutski/boot-cljs-test#33]
As boot-cljs-test doesn't create `.cljs.edn` based on options but instead depends on the default one from boot-cljs, all cljs files in fileset and compiled and loaded.

Instead if would be preferred to create a cljs.edn file which only requires the output-file namespace. Then only the namespaces which are required by test namespaces are compiled and loaded.

This  possibly has huge effect on performance with larger projects.

**Comment by crisptrutski** [comment]
This will be taken care of in #27 also, which I'm almost done with, but happy to do a point release with this solution too - thanks a lot! :smile:
