### ISSUE TITLE
Support -vv style verbosity control

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/boot-cljs-test#39]
Doo takes two output options: `debug` and `verbose`.

The most naturally-boot way to handle this would be via a "stacking" log level argument:

```
boot cljs-test                verbose=false, debug=false
boot cljs-test -v             verbose=true,  debug=false
boot cljs-test -vv            verbose=true,  debug=true
```

**Comment by Deraen** [comment]
Boot already has global verbose flag. It sets dynamic var `boot.util/*verbosity*`: https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/util.clj#L31-L43

The value can be used to set options for Doo.

**Comment by crisptrutski** [comment]
Is this the accepted practice? Only concern is that user may only be wanting "extreme cljs-test detail", and they'd need to look through the noise from other tasks, and lower level boot constructs

**Comment by crisptrutski** [comment]
Adding number flag, ie. `-v 2` to set log level. But if that's not set, it'll default to the `*verbosity*` var.
