### ISSUE TITLE
doo error on windows

### ISSUE THREAD

**Issue by laforge49** [crisptrutski/boot-cljs-test#42]
I've simplified https://github.com/aatree/aautil/ to the point where it is just a test on a very small .cljs file.

II was told on the clojurians/boot channel that it runs ok on non-windows. On windows, I am getting

Writing output.cljs.edn...
Writing clj_test\suite.cljs...
Compiling ClojureScript...
WARNING: Replacing ClojureScript compiler option :main with automatically set value.
ò output.js
Running cljs tests...
ERROR: doo was not loaded from the compiled script.

Make sure you start your tests using doo-tests or doo-all-tests
and that you include that file in your build

Ran on boot-cljs-test 0.2.1 and 0.2.2-SNAPSHOT to same effect. Got null pointer on 0.3.0-SNAPSHOT:

Writing cljs_test\suite.cljs...
Writing cljs_test\suite.cljs.edn...
Writing suite.cljs.edn...
Compiling ClojureScript...
Running cljs tests...

;; ======================================================================
;; Testing with Phantom:

```
         clojure.lang.ExceptionInfo: java.lang.NullPointerException
data: {:file
       "C:\\Users\\Bill\\AppData\\Local\\Temp\\boot.user2631139475250475313.clj",
       :line 31}
```

java.util.concurrent.ExecutionException: java.lang.NullPointerException
         java.lang.NullPointerException:
            clojure.string/replace/invokeStatic          string.clj:  101
                         clojure.string/replace          string.clj:   75
crisptrutski.boot-cljs-test/eval836/fn/fn/fn/fn  boot_cljs_test.clj:  114
   crisptrutski.boot-cljs-test/eval836/fn/fn/fn  boot_cljs_test.clj:   98
              adzerk.boot-cljs/eval326/fn/fn/fn       boot_cljs.clj:  201
              adzerk.boot-cljs/eval275/fn/fn/fn       boot_cljs.clj:  135
   crisptrutski.boot-cljs-test/eval800/fn/fn/fn  boot_cljs_test.clj:   79
                            boot.core/run-tasks            core.clj:  794
                              boot.core/boot/fn            core.clj:  804
            clojure.core/binding-conveyor-fn/fn            core.clj: 1938
                                            ...

**Comment by crisptrutski** [comment]
Thanks for the report - looks like there's an issue finding the compiled js script in the fileset. 

Will see if I can set up a VM tomorrow to poke around at this. 

If you get a chance, a printout of the fileset after the test task would be useful: make sure `:update-fs?` is true for `test-cljs`, and follow it with `show -f`

**Comment by laforge49** [comment]
C:\Users\Bill\Documents\aatree\aautil>boot test-it
Writing clj_test\suite.cljs...
Writing output.cljs.edn...
Compiling ClojureScript...
WARNING: Replacing ClojureScript compiler option :main with automatically set value.
ò output.js
Running cljs tests...
ERROR: doo was not loaded from the compiled script.

Make sure you start your tests using doo-tests or doo-all-tests
and that you include that file in your build

aautil
??? simple_test.cljs
clj_test
??? suite.cljs
output.cljs.edn
output.js
output.out
??? aautil
?   ??? simple_test.cljs
?   ??? simple_test.cljs.cache.edn
?   ??? simple_test.js
?   ??? simple_test.js.map
??? boot
?   ??? cljs
?       ??? main1059.cljs
?       ??? main1059.cljs.cache.edn
?       ??? main1059.js
?       ??? main1059.js.map
??? clj_test
?   ??? suite.cljs
?   ??? suite.cljs.cache.edn
?   ??? suite.js
?   ??? suite.js.map
??? cljs
?   ??? core.cljs
?   ??? core.js
?   ??? core.js.map
?   ??? pprint.cljs
?   ??? pprint.cljs.cache.edn
?   ??? pprint.js
?   ??? pprint.js.map
?   ??? test.cljs
?   ??? test.cljs.cache.edn
?   ??? test.js
?   ??? test.js.map
??? cljs_deps.js
??? clojure
?   ??? string.cljs
?   ??? string.cljs.cache.edn
?   ??? string.js
?   ??? string.js.map
??? doo
?   ??? runner.cljs
?   ??? runner.cljs.cache.edn
?   ??? runner.js
?   ??? runner.js.map
??? goog
?   ??? array
?   ?   ??? array.js
?   ??? asserts
?   ?   ??? asserts.js
?   ??? base.js
?   ??? debug
?   ?   ??? error.js
?   ??? deps.js
?   ??? dom
?   ?   ??? nodetype.js
?   ??? object
?   ?   ??? object.js
?   ??? string
?       ??? string.js
?       ??? stringbuffer.js
??? jx
    ??? reporter
        ??? karma.cljs
        ??? karma.cljs.cache.edn
        ??? karma.js
        ??? karma.js.map

C:\Users\Bill\Documents\aatree\aautil>

**Comment by laforge49** [comment]
Created a branch to preserve the error: https://github.com/aatree/aautil/tree/doo-error

Now I can again work on the master. :-)

**Comment by crisptrutski** [comment]
Unfortunately I didn't find the time yesterday, will take a look next weekend at the latest. Glad you're forging on undeterred :smile: 

If unix is A-OK, perhaps running worth at least having your tests run via Travis or similar in the meantime

**Comment by laforge49** [comment]
Haven't written the tests. :-)

Been busy writing sample web apps instead as demos and to exercise the
code: https://github.com/aatree/aademos

I'm sticking strictly with windows 'cause I'm really bad at linux/unix and
because life is too short. But also because I want to help move this
community to better support all those windows-only back-end commercial
devs. Its a big market that needs to be better supported. (I've also
uncovered a watch bug lately. It is incompatible with cljc files. Turns out
windows will not delete a read-only file.)

**Comment by Corkle** [comment]
I am also getting the same issue on all my Windows machines using PhantomJS:

```
Writing output.cljs.edn...
Writing clj_test\suite.cljs...
Compiling ClojureScript...
ò output.js
Running cljs tests...
ERROR: doo was not loaded from the compiled script.

Make sure you start your tests using doo-tests or doo-all-tests
and that you include that file in your build
```

Same result with boot-cljs-test 0.2.1 and 0.2.2.

**Comment by laforge49** [comment]
retested with boot 2.6.0-SNAPSHOT, as that seems to fix a lot of issues. But got the same result.

**Comment by crisptrutski** [comment]
@laforge49 would you mind if this is fixed on 0.2.2-SNAPSHOT? Suspect it was bensu/doo#97, as you are using `:phantom`

**Comment by laforge49** [comment]
No problem. Been writing all my cljc tests to run in the browser at this
point anyway. Be happy to deal with a snapshot--it is not production in any
case. :-)

**Comment by crisptrutski** [comment]
Fixed AFAIK

**Comment by laforge49** [comment]
Cool!

Unfortunately it will be a while before I can test it. :-(

**Comment by laforge49** [comment]
Tested. Happiness is.

**Comment by laforge49** [comment]
Updated https://github.com/boot-clj/boot/wiki/Running-on-Windows
