### ISSUE TITLE
permit doo options to be set

### ISSUE THREAD

**Issue by loomis** [crisptrutski/boot-cljs-test#47]
I've run into a situation in which I need to set the command line options for the phantomjs runner, specifically I need to turn off the web security for a set of tests that hit an external server.  Doo provides the ability to do this via the :paths option, but there is no way to feed this through the current version of the `test-cljs` task.

I currently have a fork where the doo options can be set. These options are simply merged into the options passed to `run-script` (currently only :ext-dir).  If that is acceptable, I can create a PR for the change.

**Comment by crisptrutski** [comment]
That sounds pretty sensible, such a PR would be welcome!

**Comment by loomis** [comment]
PR provided (#49).  The automated tests have passed and there are currently no merge conflicts.
