### ISSUE TITLE
Auto mode

### ISSUE THREAD

**Issue by cldwalker** [crisptrutski/boot-cljs-test#50]
Hi. Thanks for your plugin. Is there any interest in having the ability to auto-run tests [like the doo plugin does](https://github.com/bensu/doo/blob/master/plugin/src/leiningen/doo.clj#L218-L239)?

**Comment by martinklepsch** [comment]
I think this might already be possible by combining it with boot's watch
task?

**Comment by crisptrutski** [comment]
Yup, that's been my workflow: [example](https://github.com/crisptrutski/boot-cljs-test/blob/master/example/build.boot#L42-L45)

Closing this issue optimistically, but feel free to continue discussion here if there's still a feature gap to close 😄

**Comment by cldwalker** [comment]
Thanks for sharing. Great to see this is a first class notion in boot

**Comment by martinklepsch** [comment]
@cldwalker you're welcome, good luck! 👍
