### ISSUE TITLE
NPE running Node tests on Windows

### ISSUE THREAD

**Issue by anmonteiro** [crisptrutski/boot-cljs-test#51]
This is probably related to #31, but I'm not certain if it's specific to having external Node modules or just running Node tests on Windows.

Here's a stack trace: https://ci.appveyor.com/project/anmonteiro/lumo/build/1.0.123

**Comment by crisptrutski** [comment]
Thanks for the report, and having the stacktrace is invaluable. Looks like a general windows bug I've introduced by changing the build id to include a directory separator.

**Comment by crisptrutski** [comment]
@anmonteiro Please let me know if anything changes with the snapshot I've just deployed 😄

**Comment by anmonteiro** [comment]
@crisptrutski I think it passes the new guard but fails in a subsequent one: https://ci.appveyor.com/project/anmonteiro/lumo/build/1.0.128

**Comment by anmonteiro** [comment]
Shouldn't the output dir be there in any case? Can't Boot-cljs-test find paths with `\` too?

**Comment by crisptrutski** [comment]
I need to add more guards, but that's not the fix, that's just to reach the "nice" error on line 130. 

Need to figure out why the file isn't matching. Could replace the string with a regex that's OS agnostic.. but don't see how that's any different to just setting the right separator in the string..

**Comment by crisptrutski** [comment]
It's quite late here and I'm off to sleep, print-debugging the paths seems the simplest, maybe something obviously different about the fileset paths on windows.

**Comment by crisptrutski** [comment]
@anmonteiro did you get anywhere with this? also curious if setting a single segment `id` still works around this issue.

**Comment by anmonteiro** [comment]
I didn't investigate it, if that's what you're asking. as for the single segment, I can only say that 0.2.2 works fine.

**Comment by crisptrutski** [comment]
OK, will set myself up with some *doze and debug as soon as I get a chance :)

Perhaps try `:ids ["output"]` as an option, that should match `0.2.2`'s single segment runner namespace.

**Comment by anmonteiro** [comment]
@crisptrutski a single segment ID definitely did the trick. so we know that's the problem at least :-) thanks!

**Comment by crisptrutski** [comment]
Should be hunky dory now 😄

**Comment by anmonteiro** [comment]
awesome, did you deploy a snapshot?

**Comment by crisptrutski** [comment]
Yip it's pushed
