### ISSUE TITLE
Contents of working directory (hardlinked to fileset) removed on OSX with 0.3.1

### ISSUE THREAD

**Issue by dm3** [crisptrutski/boot-cljs-test#62]
To reproduce I run:

1) `boot test-cljs`
2) any other boot task

The `:resource-paths` directories in the working set are gone.

**Comment by MechanicalTyler** [comment]
I had this same issue.  I was able to use 0.3.0-SNAPSHOT, which doesn't have the hard links, and doesn't have this issue.

**Comment by binarykitchen** [comment]
yep, same here. it's bad.

**Comment by borkdude** [comment]
Same. Sad.

**Comment by crisptrutski** [comment]
Feel pretty bad about this - I'll see about getting the version pulled from Clojars and publishing something safer. 

"Works on my machine", not thinking things through and not sticking around until the temp folders get pruned. I'll revert to copying files, add a flag for opting into soft-links.

Update: opened https://github.com/clojars/clojars-web/issues/652

**Comment by crisptrutski** [comment]
Finally got around to this. Failed reproducing any issues on my side recent versions of OSX, not actually sure what happened. HFS should treat each link and the original as independent pointers to the inode.

Closest thing I could find was a bug in Finder where it hides linked files in some situations, but also doesn't seem to fit the bill.

If anyone has some more context to reproduce, interested for interests sake. 

Not 100% confident in my smoke tests, so letting snapshot bake for a while before releasing.
