### ISSUE TITLE
using latest clojurescript

### ISSUE THREAD

**Issue by burn2delete** [crisptrutski/boot-cljs-test#67]
There is an issue with doo while using the latest cljs, can we set the compiler options as per final comment:

https://github.com/bensu/doo/pull/141

**Comment by miikka** [comment]
I've now released [doo 0.1.8](https://github.com/bensu/doo/blob/master/CHANGELOG.md) which should fix this.

**Comment by crisptrutski** [comment]
@flyboarder will cut a release if SNAPSHOT works for you, and there's nothing else pressing to include in the next release
