### ISSUE TITLE
can't watch with symlinks

### ISSUE THREAD

**Issue by thedavidmeister** [crisptrutski/boot-cljs-test#80]
get error on the 2nd run when watching:

`java.nio.file.FileAlreadyExistsException: /Users/davidmeister/.boot/cache/tmp/Users/davidmeister/Cannabit-Cloud/73q/-ueasqk/node_modules`

**Comment by thedavidmeister** [comment]
PR up @crisptrutski

**Comment by crisptrutski** [comment]
Hi David - thanks very much for root causing and providing a fix for this issue. I am a bit nervous about an unconditional delete in this case however, would it be possible to delete existing files only if they are confirmed to be symlinks?

**Comment by thedavidmeister** [comment]
@crisptrutski maybe? i mean it sounds plausible

would you be able to test out the idea?

**Comment by thedavidmeister** [comment]
i'm checking this out now

**Comment by thedavidmeister** [comment]
@crisptrutski ok, can you check what i've done? i couldn't find anything outside `java.nio.file` that deals with the existence of a symlink.
