### ISSUE TITLE
Use new doo which supports :optimizations :none

### ISSUE THREAD

**Issue by martinklepsch** [crisptrutski/boot-cljs-test#9]
@bensu just released a new snapshot version that supports running things with optimizations :none :+1: 

https://github.com/bensu/doo#changes

**Comment by crisptrutski** [comment]
Hitting this tonight - get to drive `boot-cljs/next` at the same time :sunglasses:

**Comment by crisptrutski** [comment]
Happy to report this has landed in #10 - and snapshot is published
